API_KEY = "ISI_API_KEY_KAMU"
API_SECRET = "ISI_API_SECRET_KAMU"

TG_TOKEN = "ISI_TOKEN_BOT_TELE"
TG_CHAT_ID = "ISI_CHAT_ID_KAMU"

SYMBOLS = ["BTCUSDT", "ETHUSDT"]

LEVERAGE = 10
MARGIN_PER_TRADE = 0.5

STOP_LOSS_PCT = -0.20
TRAILING_PROFIT_PCT = 0.20

MAX_DD_BALANCE = -0.80
PROFIT_ALERT_PCT = 0.50

CHECK_INTERVAL = 3
